# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/breadth-first-fragmentation',
                'doc_host': 'https://panukorn17.github.io',
                'git_url': 'https://github.com/panukorn17/breadth-first-fragmentation',
                'lib_path': 'breadth_first_fragmentation'},
  'syms': { 'breadth_first_fragmentation.core': { 'breadth_first_fragmentation.core.foo': ( 'core.html#foo',
                                                                                            'breadth_first_fragmentation/core.py')}}}
